### PR TITLE
fix: return early when it has no entries

### PR DESCRIPTION
**Pull request by delphinus**
I found `init()` occurs errors on this line below when `self.color_table` is an empty table: `{}`. This fixes it.

https://github.com/uga-rosa/ccc.nvim/blob/3d2020703c10385970032acda4f2efe0679458d1/lua/ccc/picker/custom_entries.lua#L37

### CODE REVIEW

**Comment by uga-rosa** [comment]
LGTM.
However, if this error occurs, it means that it is not being used correctly, right? There must be some user error, such as an empty table being passed to new(), or the format of the passed table is wrong.
So I would like a warning using vim.notify(). Instead of explaining in detail, it is enough to direct them to help.

**Comment by delphinus** [comment]
@uga-rosa I see. Surely, it is hospitable to teach users to set some entries in the table. I found `utils.notify` function, but it always informs messages with INFO level. For this purpose, should I add another function with a new name, such as, `utils.warn`?

**Comment by uga-rosa** [comment]
`utils.notify()`, I'm only using it in one place. All it does is put `string.format()` in between, so I think I'll remove it.
Please use `vim.notify()` directly in this PR.

**Comment by delphinus** [comment]
When I added a commit 86724b6, it shows many notifications because `parse_color()` is called many time. So I've added 19e1ab9 and it shows a notification only once even when it calls `parse_color()` multi times.

**Comment by uga-rosa** [comment]
You can use `vim.notify_once()`.

**Comment by delphinus** [comment]
Good catch 👍🏼 I've fixed it.

**Comment by uga-rosa** [comment]
LGTM! Ty!

**Pull request merged**
