### PR TITLE
feat: support textDocument/documentColor for highlighter

### PR DESCRIPTION
**Pull request by uga-rosa**

### CODE REVIEW

**Comment by uga-rosa** [comment]
The default value is true for testing, but will be corrected to false before merging.

**Comment by uga-rosa** [comment]
@adelarsq Have you tried?

**Comment by adelarsq** [comment]
@uga-rosa I still wasn't able to test. I will test today and see how it goes.

**Comment by adelarsq** [comment]
@uga-rosa I am trying to test. How to know for sure that a color was picked by LSP?

**Comment by adelarsq** [comment]
@uga-rosa I have tested today. It's working! 🎉 

image

**Comment by uga-rosa** [comment]
@adelarsq Can I use that screenshot in the README as an example of colorizer?

**Comment by adelarsq** [comment]
@uga-rosa I will prepare a better image. Just a minute

**Comment by adelarsq** [comment]
image

**Comment by uga-rosa** [comment]
Ty!

**Pull request merged**
